services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
      - ${FILES_MEDIA_PATH-/home/$USER/videos}:/app/public/media
    working_dir: /app
